
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-test-analysis using AI Type  and AI Model

ROOST_METHOD_HASH=toString_3eeb15b3bc
ROOST_METHOD_SIG_HASH=toString_bbffdadaa2

Scenario 1: Testing the toString method when the obscured value is null

Details:
    TestName: testToStringWithNullObscured.
    Description: This test will verify if the toString method properly handles a null value for the obscured field.
Execution:
    Arrange: Create a CredentialsObscuredGet200Response object and do not set the obscured value.
    Act: Invoke the toString method on the created object.
    Assert: Assert that the returned string correctly represents the object with a null obscured value.
Validation:
    The assertion verifies that the toString method correctly handles null values. The expected result is a string representation of the object with "null" for the obscured value. This test is essential to ensure that the toString method won't throw a NullPointerException when the obscured value is null.

Scenario 2: Testing the toString method when the obscured value is true

Details:
    TestName: testToStringWithTrueObscured.
    Description: This test will verify if the toString method correctly displays an object with the obscured value set to true.
Execution:
    Arrange: Create a CredentialsObscuredGet200Response object and set the obscured value to true.
    Act: Invoke the toString method on the created object.
    Assert: Assert that the returned string correctly represents the object with a true obscured value.
Validation:
    The assertion verifies that the toString method correctly represents an object with a true obscured value. The expected result is a string representation of the object with "true" for the obscured value. This test is crucial to ensure that the toString method accurately reflects the state of the object.

Scenario 3: Testing the toString method when the obscured value is false

Details:
    TestName: testToStringWithFalseObscured.
    Description: This test will verify if the toString method correctly displays an object with the obscured value set to false.
Execution:
    Arrange: Create a CredentialsObscuredGet200Response object and set the obscured value to false.
    Act: Invoke the toString method on the created object.
    Assert: Assert that the returned string correctly represents the object with a false obscured value.
Validation:
    The assertion verifies that the toString method correctly represents an object with a false obscured value. The expected result is a string representation of the object with "false" for the obscured value. This test is crucial to ensure that the toString method accurately reflects the state of the object.
*/

// ********RoostGPT********

package org.openapitools.model;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;
import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.*;
import javax.annotation.Generated;

public class CredentialsObscuredGet200ResponseToStringTest {

	@Test
	@Tag("valid")
	public void testToStringWithNullObscured() {
		// Arrange
		CredentialsObscuredGet200Response response = new CredentialsObscuredGet200Response();
		response.setObscured(null);
		// Act
		String actual = response.toString();
		// Assert
		String expected = "class CredentialsObscuredGet200Response {\n    obscured: null\n}";
		assertEquals(expected, actual);
	}

	@Test
	@Tag("valid")
	public void testToStringWithTrueObscured() {
		// Arrange
		CredentialsObscuredGet200Response response = new CredentialsObscuredGet200Response();
		response.setObscured(true);
		// Act
		String actual = response.toString();
		// Assert
		String expected = "class CredentialsObscuredGet200Response {\n    obscured: true\n}";
		assertEquals(expected, actual);
	}

	@Test
	@Tag("valid")
	public void testToStringWithFalseObscured() {
		// Arrange
		CredentialsObscuredGet200Response response = new CredentialsObscuredGet200Response();
		response.setObscured(false);
		// Act
		String actual = response.toString();
		// Assert
		String expected = "class CredentialsObscuredGet200Response {\n    obscured: false\n}";
		assertEquals(expected, actual);
	}

}