
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-test-analysis using AI Type  and AI Model

ROOST_METHOD_HASH=obscured_4ae41e6cc1
ROOST_METHOD_SIG_HASH=obscured_5bb44ad197

"""
Scenario 1: Test when the Obscured attribute is set to true.

Details:
  TestName: testSettingObscuredToTrue.
  Description: This test is meant to check the functionality of the method when the obscured attribute is set to true. The target scenario is to ensure that the method can handle and correctly process a boolean value of true.
Execution:
  Arrange: Instantiate the CredentialsObscuredGet200Response class and set the obscured attribute to true.
  Act: Invoke the obscured() method with the parameter set to true.
  Assert: Use JUnit assertions to verify that the obscured attribute of the class instance is now true.
Validation:
  The assertion aims to verify that the obscured attribute has been correctly set to true. The expected result is that the obscured attribute of the class instance is now true. This test is significant as it confirms that the method can correctly process a true boolean value.

Scenario 2: Test when the Obscured attribute is set to false.

Details:
  TestName: testSettingObscuredToFalse.
  Description: This test is meant to check the functionality of the method when the obscured attribute is set to false. The target scenario is to ensure that the method can handle and correctly process a boolean value of false.
Execution:
  Arrange: Instantiate the CredentialsObscuredGet200Response class and set the obscured attribute to false.
  Act: Invoke the obscured() method with the parameter set to false.
  Assert: Use JUnit assertions to verify that the obscured attribute of the class instance is now false.
Validation:
  The assertion aims to verify that the obscured attribute has been correctly set to false. The expected result is that the obscured attribute of the class instance is now false. This test is significant as it confirms that the method can correctly process a false boolean value.

Scenario 3: Test when the Obscured attribute is set to null.

Details:
  TestName: testSettingObscuredToNull.
  Description: This test is meant to check the functionality of the method when the obscured attribute is set to null. The target scenario is to ensure that the method can handle and correctly process a null value.
Execution:
  Arrange: Instantiate the CredentialsObscuredGet200Response class and set the obscured attribute to null.
  Act: Invoke the obscured() method with the parameter set to null.
  Assert: Use JUnit assertions to verify that the obscured attribute of the class instance is now null.
Validation:
  The assertion aims to verify that the obscured attribute has been correctly set to null. The expected result is that the obscured attribute of the class instance is now null. This test is significant as it confirms that the method can correctly process a null value.

Scenario 4: Test the Obscured attribute's consistency.

Details:
  TestName: testObscuredAttributeConsistency.
  Description: This test is meant to check the functionality of the method when the obscured attribute is set multiple times. The target scenario is to ensure that the method maintains the consistency of the obscured attribute.
Execution:
  Arrange: Instantiate the CredentialsObscuredGet200Response class and set the obscured attribute to true.
  Act: Invoke the obscured() method with the parameter set to false.
  Assert: Use JUnit assertions to verify that the obscured attribute of the class instance is now false.
Validation:
  The assertion aims to verify that the obscured attribute has been correctly updated to false. The expected result is that the obscured attribute of the class instance is now false, regardless of its previous state. This test is significant as it confirms that the method correctly updates the obscured attribute, maintaining its consistency.
"""
*/

// ********RoostGPT********

package org.openapitools.model;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.openapitools.model.CredentialsObscuredGet200Response;
import org.junit.jupiter.api.*;
import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.*;
import javax.annotation.Generated;

public class CredentialsObscuredGet200ResponseObscuredTest {

	@Test
	@Tag("valid")
	public void testSettingObscuredToTrue() {
		// Arrange
		CredentialsObscuredGet200Response testResponse = new CredentialsObscuredGet200Response();
		// Act
		testResponse.obscured(true);
		// Assert
		assertTrue(testResponse.getObscured());
	}

	@Test
	@Tag("valid")
	public void testSettingObscuredToFalse() {
		// Arrange
		CredentialsObscuredGet200Response testResponse = new CredentialsObscuredGet200Response();
		// Act
		testResponse.obscured(false);
		// Assert
		assertFalse(testResponse.getObscured());
	}

	@Test
	@Tag("invalid")
	public void testSettingObscuredToNull() {
		// Arrange
		CredentialsObscuredGet200Response testResponse = new CredentialsObscuredGet200Response();
		// Act
		testResponse.obscured(null);
		// Assert
		assertNull(testResponse.getObscured());
	}

	@Test
	@Tag("boundary")
	public void testObscuredAttributeConsistency() {
		// Arrange
		CredentialsObscuredGet200Response testResponse = new CredentialsObscuredGet200Response();
		testResponse.obscured(true);
		// Act
		testResponse.obscured(false);
		// Assert
		assertFalse(testResponse.getObscured());
	}

}