
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-test-analysis using AI Type  and AI Model

ROOST_METHOD_HASH=getObscured_796c9349ae
ROOST_METHOD_SIG_HASH=getObscured_768abccef5

"""
Scenario 1: Test to check if the getObscured method returns the correct value when it is set to true

Details:
  TestName: testGetObscuredReturnsTrue
  Description: This test is meant to check the getObscured method. The test will set the obscured value to true and then verify if the getObscured method returns true.
Execution:
  Arrange: Create an instance of the CredentialsObscuredGet200Response class and set the obscured value to true.
  Act: Invoke the getObscured method.
  Assert: Use JUnit assertions to check if the returned value is true.
Validation:
  The assertion aims to verify that the getObscured method returns the correct value that was set. This test is significant in ensuring the getObscured method functions correctly when the obscured value is true.

Scenario 2: Test to check if the getObscured method returns the correct value when it is set to false

Details:
  TestName: testGetObscuredReturnsFalse
  Description: This test is meant to check the getObscured method. The test will set the obscured value to false and then verify if the getObscured method returns false.
Execution:
  Arrange: Create an instance of the CredentialsObscuredGet200Response class and set the obscured value to false.
  Act: Invoke the getObscured method.
  Assert: Use JUnit assertions to check if the returned value is false.
Validation:
  The assertion aims to verify that the getObscured method returns the correct value that was set. This test is significant in ensuring the getObscured method functions correctly when the obscured value is false.

Scenario 3: Test to check if the getObscured method returns null when the obscured value is not set

Details:
  TestName: testGetObscuredReturnsNull
  Description: This test is meant to check the getObscured method. The test will not set any value to obscured and then verify if the getObscured method returns null.
Execution:
  Arrange: Create an instance of the CredentialsObscuredGet200Response class without setting any value to obscured.
  Act: Invoke the getObscured method.
  Assert: Use JUnit assertions to check if the returned value is null.
Validation:
  The assertion aims to verify that the getObscured method returns null when no value is set to obscured. This test is significant in ensuring the getObscured method functions correctly when no value is set to obscured.
"""
*/

// ********RoostGPT********

package org.openapitools.model;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.*;
import javax.annotation.Generated;

public class CredentialsObscuredGet200ResponseGetObscuredTest {

	@Test
	@Tag("valid")
	public void testGetObscuredReturnsTrue() {
		// Arrange
		CredentialsObscuredGet200Response testInstance = new CredentialsObscuredGet200Response();
		testInstance.setObscured(true);
		// Act
		Boolean result = testInstance.getObscured();
		// Assert
		assertTrue(result, "Expected getObscured to return true, but it returned " + result);
	}

	@Test
	@Tag("valid")
	public void testGetObscuredReturnsFalse() {
		// Arrange
		CredentialsObscuredGet200Response testInstance = new CredentialsObscuredGet200Response();
		testInstance.setObscured(false);
		// Act
		Boolean result = testInstance.getObscured();
		// Assert
		assertFalse(result, "Expected getObscured to return false, but it returned " + result);
	}

	@Test
	@Tag("boundary")
	public void testGetObscuredReturnsNull() {
		// Arrange
		CredentialsObscuredGet200Response testInstance = new CredentialsObscuredGet200Response();
		// Act
		Boolean result = testInstance.getObscured();
		// Assert
		assertNull(result, "Expected getObscured to return null, but it returned " + result);
	}

}