
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-unit-test using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=getObscured_ad79838ac5
ROOST_METHOD_SIG_HASH=getObscured_5d683707b9

```plaintext
Scenario 1: Verify that getObscured returns null when obscured field is not set

Details:
  TestName: obtainsNullWhenObscuredNotSet
  Description: This test verifies that the getObscured method returns null when the obscured field has not been set.
Execution:
  Arrange: Create an instance of CredentialsObscuredGet200Response without setting the obscured field.
  Act: Invoke the getObscured method on the instance.
  Assert: Use JUnit's assertNull to verify that the returned value is null.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 2: Verify that getObscured returns true when obscured field is set to true

Details:
  TestName: obtainsTrueWhenObscuredSetToTrue
  Description: This test verifies that the getObscured method returns true when the obscured field is explicitly set to true.
Execution:
  Arrange: Create an instance of CredentialsObscuredGet200Response and set the obscured field to true using the obscured method.
  Act: Invoke the getObscured method on the instance.
  Assert: Use JUnit's assertTrue to verify that the returned value is true.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 3: Verify that getObscured returns false when obscured field is set to false

Details:
  TestName: obtainsFalseWhenObscuredSetToFalse
  Description: This test verifies that the getObscured method returns false when the obscured field is explicitly set to false.
Execution:
  Arrange: Create an instance of CredentialsObscuredGet200Response and set the obscured field to false using the obscured method.
  Act: Invoke the getObscured method on the instance.
  Assert: Use JUnit's assertFalse to verify that the returned value is false.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 4: Verify that getObscured returns the correct value after setting it using setObscured method

Details:
  TestName: obtainsCorrectValueAfterSetObscured
  Description: This test verifies that the getObscured method returns the value set using the setObscured method.
Execution:
  Arrange: Create an instance of CredentialsObscuredGet200Response and set the obscured field to true using the setObscured method.
  Act: Invoke the getObscured method on the instance.
  Assert: Use JUnit's assertTrue to verify that the returned value is true.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 5: Verify that getObscured returns the correct value after chaining the obscured method

Details:
  TestName: obtainsCorrectValueAfterChainingObscured
  Description: This test verifies that the getObscured method returns the value set using the chained obscured method.
Execution:
  Arrange: Create an instance of CredentialsObscuredGet200Response and chain the obscured method to set the obscured field to true.
  Act: Invoke the getObscured method on the instance.
  Assert: Use JUnit's assertTrue to verify that the returned value is true.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 6: Verify that getObscured returns null after setting it to null using setObscured method

Details:
  TestName: obtainsNullAfterSettingObscuredToNull
  Description: This test verifies that the getObscured method returns null after setting the obscured field to null using the setObscured method.
Execution:
  Arrange: Create an instance of CredentialsObscuredGet200Response and set the obscured field to null using the setObscured method.
  Act: Invoke the getObscured method on the instance.
  Assert: Use JUnit's assertNull to verify that the returned value is null.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 7: Verify that getObscured returns null after chaining the obscured method to null

Details:
  TestName: obtainsNullAfterChainingObscuredToNull
  Description: This test verifies that the getObscured method returns null after chaining the obscured method to null.
Execution:
  Arrange: Create an instance of CredentialsObscuredGet200Response and chain the obscured method to set the obscured field to null.
  Act: Invoke the getObscured method on the instance.
  Assert: Use JUnit's assertNull to verify that the returned value is null.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```
*/

// ********RoostGPT********

package org.openapitools.model;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.openapitools.model.CredentialsObscuredGet200Response;
import org.junit.jupiter.api.*;
import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.*;
import javax.annotation.Generated;

public class CredentialsObscuredGet200ResponseGetObscuredTest {

	@Test
	@Tag("valid")
	public void obtainsNullWhenObscuredNotSet() {
		CredentialsObscuredGet200Response response = new CredentialsObscuredGet200Response();
		assertNull(response.getObscured());
	}

	@Test
	@Tag("valid")
	public void obtainsTrueWhenObscuredSetToTrue() {
		CredentialsObscuredGet200Response response = new CredentialsObscuredGet200Response().obscured(true);
		assertTrue(response.getObscured());
	}

	@Test
	@Tag("valid")
	public void obtainsFalseWhenObscuredSetToFalse() {
		CredentialsObscuredGet200Response response = new CredentialsObscuredGet200Response().obscured(false);
		assertFalse(response.getObscured());
	}

	@Test
	@Tag("valid")
	public void obtainsCorrectValueAfterSetObscured() {
		CredentialsObscuredGet200Response response = new CredentialsObscuredGet200Response();
		response.setObscured(true);
		assertTrue(response.getObscured());
	}

	@Test
	@Tag("valid")
	public void obtainsCorrectValueAfterChainingObscured() {
		CredentialsObscuredGet200Response response = new CredentialsObscuredGet200Response().obscured(true);
		assertTrue(response.getObscured());
	}

	@Test
	@Tag("valid")
	public void obtainsNullAfterSettingObscuredToNull() {
		CredentialsObscuredGet200Response response = new CredentialsObscuredGet200Response();
		response.setObscured(null);
		assertNull(response.getObscured());
	}

	@Test
	@Tag("valid")
	public void obtainsNullAfterChainingObscuredToNull() {
		CredentialsObscuredGet200Response response = new CredentialsObscuredGet200Response().obscured(null);
		assertNull(response.getObscured());
	}

}