
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-test-analysis using AI Type  and AI Model

ROOST_METHOD_HASH=equals_082a9e7881
ROOST_METHOD_SIG_HASH=equals_ded257778a

"""
Scenario 1: Test when the objects are same
Details:
  TestName: testEqualsForSameObject
  Description: This test is meant to check if the equals method returns true when the same object is passed to it.
Execution:
  Arrange: Create a new instance of CredentialsObscuredGet200Response and set the obscured property.
  Act: Call the equals method on the instance and pass the same instance as argument.
  Assert: Assert that the equals method returns true.
Validation:
  The assertion verifies that the equals method returns true when the same object is passed as an argument. This behavior is as per the Java contract of equals method.

Scenario 2: Test when the objects are equal
Details:
  TestName: testEqualsForEqualObjects
  Description: This test is meant to check if the equals method returns true when two different instances with same properties are passed to it.
Execution:
  Arrange: Create two different instances of CredentialsObscuredGet200Response and set the same obscured property for both.
  Act: Call the equals method on one instance and pass the other instance as argument.
  Assert: Assert that the equals method returns true.
Validation:
  The assertion verifies that the equals method returns true when two different instances with same properties are passed to it. This behavior is as per the Java contract of equals method.

Scenario 3: Test when the objects are not equal
Details:
  TestName: testEqualsForNotEqualObjects
  Description: This test is meant to check if the equals method returns false when two different instances with different properties are passed to it.
Execution:
  Arrange: Create two different instances of CredentialsObscuredGet200Response and set different obscured property for both.
  Act: Call the equals method on one instance and pass the other instance as argument.
  Assert: Assert that the equals method returns false.
Validation:
  The assertion verifies that the equals method returns false when two different instances with different properties are passed to it. This behavior is as per the Java contract of equals method.

Scenario 4: Test when a null object is passed
Details:
  TestName: testEqualsForNullObject
  Description: This test is meant to check if the equals method returns false when a null object is passed to it.
Execution:
  Arrange: Create a new instance of CredentialsObscuredGet200Response and set the obscured property.
  Act: Call the equals method on the instance and pass null as argument.
  Assert: Assert that the equals method returns false.
Validation:
  The assertion verifies that the equals method returns false when a null object is passed as an argument. This behavior is as per the Java contract of equals method.

Scenario 5: Test when objects are of different types
Details:
  TestName: testEqualsForDifferentTypes
  Description: This test is meant to check if the equals method returns false when an object of a different type is passed to it.
Execution:
  Arrange: Create a new instance of CredentialsObscuredGet200Response and set the obscured property.
  Act: Call the equals method on the instance and pass an object of a different type as argument.
  Assert: Assert that the equals method returns false.
Validation:
  The assertion verifies that the equals method returns false when an object of a different type is passed as an argument. This behavior is as per the Java contract of equals method.
"""
*/

// ********RoostGPT********

package org.openapitools.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.*;
import javax.annotation.Generated;

public class CredentialsObscuredGet200ResponseEqualsTest {

	private CredentialsObscuredGet200Response credentialsObscuredGet200Response1;

	private CredentialsObscuredGet200Response credentialsObscuredGet200Response2;

	@BeforeEach
	public void setUp() {
		credentialsObscuredGet200Response1 = new CredentialsObscuredGet200Response();
		credentialsObscuredGet200Response2 = new CredentialsObscuredGet200Response();
	}

	@Test
	@Tag("valid")
	public void testEqualsForSameObject() {
		assertTrue(credentialsObscuredGet200Response1.equals(credentialsObscuredGet200Response1));
	}

	@Test
	@Tag("valid")
	public void testEqualsForEqualObjects() {
		credentialsObscuredGet200Response1.setObscured(true);
		credentialsObscuredGet200Response2.setObscured(true);
		assertTrue(credentialsObscuredGet200Response1.equals(credentialsObscuredGet200Response2));
	}

	@Test
	@Tag("invalid")
	public void testEqualsForNotEqualObjects() {
		credentialsObscuredGet200Response1.setObscured(true);
		credentialsObscuredGet200Response2.setObscured(false);
		assertFalse(credentialsObscuredGet200Response1.equals(credentialsObscuredGet200Response2));
	}

	@Test
	@Tag("invalid")
	public void testEqualsForNullObject() {
		assertFalse(credentialsObscuredGet200Response1.equals(null));
	}

	@Test
	@Tag("invalid")
	public void testEqualsForDifferentTypes() {
		assertFalse(credentialsObscuredGet200Response1.equals(new Object()));
	}

}