
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-test-analysis using AI Type  and AI Model

ROOST_METHOD_HASH=hashCode_0d6e508e79
ROOST_METHOD_SIG_HASH=hashCode_44411a81c8

"""
Scenario 1: Testing the hashCode method with status set to a non-null string
TestName: testHashCodeWithNonNullStatus
Description: This test is meant to check the hashCode method when the status field is set to a non-null string.
Execution:
  Arrange: Create a LoginButtonStatusGet200Response object and set the status field to a non-null string.
  Act: Invoke the hashCode method on the created object.
  Assert: Assert that the returned hashCode is equal to the hashCode of the status string.
Validation:
  The assertion verifies that the hashCode method correctly computes the hash code of the status string. This is important to ensure that objects with the same status have the same hash code, enabling efficient lookup and retrieval in collections.

Scenario 2: Testing the hashCode method with status set to null
TestName: testHashCodeWithNullStatus
Description: This test is meant to check the hashCode method when the status field is set to null.
Execution:
  Arrange: Create a LoginButtonStatusGet200Response object and set the status field to null.
  Act: Invoke the hashCode method on the created object.
  Assert: Assert that the returned hashCode is equal to zero.
Validation:
  The assertion verifies that the hashCode method correctly handles null values for the status field. This is important to prevent NullPointerExceptions when computing the hash code of an object with a null status.

Scenario 3: Testing the hashCode method on two objects with the same status
TestName: testHashCodeOnEqualObjects
Description: This test is meant to check the hashCode method on two objects with the same status.
Execution:
  Arrange: Create two LoginButtonStatusGet200Response objects and set their status fields to the same non-null string.
  Act: Invoke the hashCode method on both objects.
  Assert: Assert that the returned hashCodes are equal.
Validation:
  The assertion verifies that the hashCode method returns the same hash code for two objects with the same status. This is important to ensure that equal objects have the same hash code, as required by the contract of the hashCode method in the Object class.
"""
*/

// ********RoostGPT********

package org.openapitools.model;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import org.junit.jupiter.api.*;
import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.*;
import javax.annotation.Generated;

public class LoginButtonStatusGet200ResponseHashCodeTest {

	@Test
	@Tag("valid")
	public void testHashCodeWithNonNullStatus() {
		LoginButtonStatusGet200Response response = new LoginButtonStatusGet200Response();
		response.setStatus("active");
		int expectedHashCode = Objects.hash("active");
		assertEquals(expectedHashCode, response.hashCode());
	}

	@Test
	@Tag("boundary")
	public void testHashCodeWithNullStatus() {
		LoginButtonStatusGet200Response response = new LoginButtonStatusGet200Response();
		response.setStatus(null);
		int expectedHashCode = Objects.hash((Object) null);
		assertEquals(expectedHashCode, response.hashCode());
	}

	@Test
	@Tag("valid")
	public void testHashCodeOnEqualObjects() {
		LoginButtonStatusGet200Response response1 = new LoginButtonStatusGet200Response();
		response1.setStatus("active");
		LoginButtonStatusGet200Response response2 = new LoginButtonStatusGet200Response();
		response2.setStatus("active");
		assertEquals(response1.hashCode(), response2.hashCode());
	}

}