
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-test-analysis using AI Type  and AI Model

ROOST_METHOD_HASH=equals_c359bb3fac
ROOST_METHOD_SIG_HASH=equals_ded257778a

"""
Scenario 1: Test for checking equality with the same object
Details:
  TestName: testEqualsWithSameObject
  Description: This test checks the equals method when the same object is passed as a parameter. The equals method should return true when the same object is compared with itself.
  Execution:
    Arrange: Create an instance of LoginButtonStatusGet200Response and set a status.
    Act: Invoke the equals method with the same object as parameter.
    Assert: Assert that the equals method returns true.
  Validation:
    The equals method should return true when an object is compared with itself. This validates the reflexivity property of the equals method.

Scenario 2: Test for checking equality with a null object
Details:
  TestName: testEqualsWithNullObject
  Description: This test checks the equals method when null is passed as a parameter. The equals method should return false when null is compared.
  Execution:
    Arrange: Create an instance of LoginButtonStatusGet200Response and set a status.
    Act: Invoke the equals method with null as parameter.
    Assert: Assert that the equals method returns false.
  Validation:
    The equals method should return false when compared with null. This validates the non-nullity property of the equals method.

Scenario 3: Test for checking equality with a different class object
Details:
  TestName: testEqualsWithDifferentClassObject
  Description: This test checks the equals method when an object of a different class is passed as a parameter.
  Execution:
    Arrange: Create an instance of LoginButtonStatusGet200Response and set a status. Also, create an object of a different class.
    Act: Invoke the equals method with the different class object as parameter.
    Assert: Assert that the equals method returns false.
  Validation:
    The equals method should return false when an object of a different class is compared. This validates the class check property of the equals method.

Scenario 4: Test for checking equality with an object having the same status
Details:
  TestName: testEqualsWithSameStatusObject
  Description: This test checks the equals method when an object with the same status is passed as a parameter.
  Execution:
    Arrange: Create two instances of LoginButtonStatusGet200Response and set the same status for both.
    Act: Invoke the equals method with the second object as parameter.
    Assert: Assert that the equals method returns true.
  Validation:
    The equals method should return true when an object with the same status is compared. This validates the equality property of the equals method when the statuses are same.

Scenario 5: Test for checking equality with an object having a different status
Details:
  TestName: testEqualsWithDifferentStatusObject
  Description: This test checks the equals method when an object with a different status is passed as a parameter.
  Execution:
    Arrange: Create two instances of LoginButtonStatusGet200Response and set different statuses for both.
    Act: Invoke the equals method with the second object as parameter.
    Assert: Assert that the equals method returns false.
  Validation:
    The equals method should return false when an object with a different status is compared. This validates the equality property of the equals method when the statuses are different.
"""
*/

// ********RoostGPT********

package org.openapitools.model;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.*;
import javax.annotation.Generated;

public class LoginButtonStatusGet200ResponseEqualsTest {

	@Test
	@Tag("valid")
	public void testEqualsWithSameObject() {
		LoginButtonStatusGet200Response response = new LoginButtonStatusGet200Response();
		response.setStatus("Active");
		assertTrue(response.equals(response));
	}

	@Test
	@Tag("invalid")
	public void testEqualsWithNullObject() {
		LoginButtonStatusGet200Response response = new LoginButtonStatusGet200Response();
		response.setStatus("Active");
		assertFalse(response.equals(null));
	}

	@Test
	@Tag("invalid")
	public void testEqualsWithDifferentClassObject() {
		LoginButtonStatusGet200Response response = new LoginButtonStatusGet200Response();
		response.setStatus("Active");
		String differentClassObject = "SomeString";
		assertFalse(response.equals(differentClassObject));
	}

	@Test
	@Tag("valid")
	public void testEqualsWithSameStatusObject() {
		LoginButtonStatusGet200Response response1 = new LoginButtonStatusGet200Response();
		LoginButtonStatusGet200Response response2 = new LoginButtonStatusGet200Response();
		response1.setStatus("Active");
		response2.setStatus("Active");
		assertTrue(response1.equals(response2));
	}

	@Test
	@Tag("invalid")
	public void testEqualsWithDifferentStatusObject() {
		LoginButtonStatusGet200Response response1 = new LoginButtonStatusGet200Response();
		LoginButtonStatusGet200Response response2 = new LoginButtonStatusGet200Response();
		response1.setStatus("Active");
		response2.setStatus("Inactive");
		assertFalse(response1.equals(response2));
	}

}