
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-test-analysis using AI Type  and AI Model

ROOST_METHOD_HASH=equals_c359bb3fac
ROOST_METHOD_SIG_HASH=equals_ded257778a

Scenario 1: Validate equal method when objects are identical
Details:
  TestName: validateEqualsForIdenticalObjects
  Description: This test will verify the equals method when the same object is passed as a parameter.
Execution:
  Arrange: Create a LoginButtonStatusGet200Response object and assign it to two different references.
  Act: Invoke the equals method by passing one reference as a parameter.
  Assert: Assert that the equals method returns true.
Validation:
  The assertion verifies that the equals method returns true when the same object is compared. This is expected as per the Java equals contract.

Scenario 2: Validate equal method when objects are equal but not identical
Details:
  TestName: validateEqualsForEqualObjects
  Description: This test will verify the equals method when two different objects with the same status are compared.
Execution:
  Arrange: Create two LoginButtonStatusGet200Response objects with the same status.
  Act: Invoke the equals method by passing one object as a parameter to the equals method of the other.
  Assert: Assert that the equals method returns true.
Validation:
  The assertion verifies that the equals method returns true when two different objects with the same status are compared. This is expected as per the implementation of the equals method in the LoginButtonStatusGet200Response class.

Scenario 3: Validate equal method when objects are not equal
Details:
  TestName: validateEqualsForNotEqualObjects
  Description: This test will verify the equals method when two different objects with different statuses are compared.
Execution:
  Arrange: Create two LoginButtonStatusGet200Response objects with different statuses.
  Act: Invoke the equals method by passing one object as a parameter to the equals method of the other.
  Assert: Assert that the equals method returns false.
Validation:
  The assertion verifies that the equals method returns false when two different objects with different statuses are compared. This is expected as per the implementation of the equals method in the LoginButtonStatusGet200Response class.

Scenario 4: Validate equal method when compared with null
Details:
  TestName: validateEqualsForNullObject
  Description: This test will verify the equals method when null is passed as a parameter.
Execution:
  Arrange: Create a LoginButtonStatusGet200Response object.
  Act: Invoke the equals method by passing null as a parameter.
  Assert: Assert that the equals method returns false.
Validation:
  The assertion verifies that the equals method returns false when null is passed as a parameter. This is expected as per the Java equals contract.
*/

// ********RoostGPT********

package org.openapitools.model;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.*;
import javax.annotation.Generated;

public class LoginButtonStatusGet200ResponseEqualsTest {

	@Test
	@Tag("valid")
	public void validateEqualsForIdenticalObjects() {
		LoginButtonStatusGet200Response response1 = new LoginButtonStatusGet200Response();
		response1.setStatus("ACTIVE");
		LoginButtonStatusGet200Response response2 = response1;
		assertTrue(response1.equals(response2));
	}

	@Test
	@Tag("valid")
	public void validateEqualsForEqualObjects() {
		LoginButtonStatusGet200Response response1 = new LoginButtonStatusGet200Response();
		response1.setStatus("ACTIVE");
		LoginButtonStatusGet200Response response2 = new LoginButtonStatusGet200Response();
		response2.setStatus("ACTIVE");
		assertTrue(response1.equals(response2));
	}

	@Test
	@Tag("invalid")
	public void validateEqualsForNotEqualObjects() {
		LoginButtonStatusGet200Response response1 = new LoginButtonStatusGet200Response();
		response1.setStatus("ACTIVE");
		LoginButtonStatusGet200Response response2 = new LoginButtonStatusGet200Response();
		response2.setStatus("INACTIVE");
		assertFalse(response1.equals(response2));
	}

	@Test
	@Tag("invalid")
	public void validateEqualsForNullObject() {
		LoginButtonStatusGet200Response response1 = new LoginButtonStatusGet200Response();
		response1.setStatus("ACTIVE");
		assertFalse(response1.equals(null));
	}

}