
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-test-analysis using AI Type  and AI Model

ROOST_METHOD_HASH=hashCode_185487e55c
ROOST_METHOD_SIG_HASH=hashCode_44411a81c8

Scenario 1: Test to verify correctness of hashCode for LoginPostRequest object

Details:
  TestName: verifyHashCodeForCorrectLoginPostRequest
  Description: This test is meant to check whether the hashCode method generates the correct hash code for a LoginPostRequest object.
Execution:
  Arrange: Create a LoginPostRequest object by setting username and password.
  Act: Invoke the hashCode method on the created LoginPostRequest object.
  Assert: Use JUnit assertions to compare the actual hash code against the expected hash code.
Validation:
  The assertion aims to verify that the hash code generated by the hashCode method is correct. The expected result is determined by calling Objects.hash with the username and password of the LoginPostRequest object. This test ensures the integrity of the hashCode method.

Scenario 2: Test to verify hashCode consistency for LoginPostRequest object

Details:
  TestName: verifyHashCodeConsistency
  Description: This test is meant to check the consistency of the hashCode method, i.e., whether it generates the same hash code for the same LoginPostRequest object upon multiple invocations.
Execution:
  Arrange: Create a LoginPostRequest object by setting username and password.
  Act: Invoke the hashCode method on the created LoginPostRequest object multiple times.
  Assert: Use JUnit assertions to compare the hash codes generated across multiple invocations to ensure they are the same.
Validation:
  The assertion aims to verify the consistency of the hashCode method. According to the contract of the hashCode method in Java, multiple invocations of hashCode on the same object should return the same integer value, provided no information used in equals comparisons is modified. This test ensures adherence to this contract.

Scenario 3: Test to verify hashCode difference for distinct LoginPostRequest objects

Details:
  TestName: verifyHashCodeDifferenceForDistinctObjects
  Description: This test is meant to check whether the hashCode method generates different hash codes for distinct LoginPostRequest objects.
Execution:
  Arrange: Create two distinct LoginPostRequest objects by setting different usernames and passwords.
  Act: Invoke the hashCode method on both LoginPostRequest objects.
  Assert: Use JUnit assertions to compare the hash codes generated for both objects to ensure they are not the same.
Validation:
  The assertion aims to verify that the hashCode method generates different hash codes for distinct objects. This is important for the correct functioning of hash-based collections such as HashMap, HashSet, etc. This test ensures that the hashCode method respects this aspect of the hashCode contract in Java.
*/

// ********RoostGPT********

package org.openapitools.model;

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.*;
import javax.annotation.Generated;

class LoginPostRequestHashCodeTest {

	@Test
	@Tag("valid")
	void verifyHashCodeForCorrectLoginPostRequest() {
		LoginPostRequest loginPostRequest = new LoginPostRequest();
		loginPostRequest.setUsername("testUser");
		loginPostRequest.setPassword("testPass123");
		int expectedHashCode = Objects.hash("testUser", "testPass123");
		int actualHashCode = loginPostRequest.hashCode();
		assertEquals(expectedHashCode, actualHashCode, "The hash code generated is not correct.");
	}

	@Test
	@Tag("valid")
	void verifyHashCodeConsistency() {
		LoginPostRequest loginPostRequest = new LoginPostRequest();
		loginPostRequest.setUsername("testUser");
		loginPostRequest.setPassword("testPass123");
		int hashCode1 = loginPostRequest.hashCode();
		int hashCode2 = loginPostRequest.hashCode();
		assertEquals(hashCode1, hashCode2, "The hash code is not consistent across multiple invocations.");
	}

	@Test
	@Tag("valid")
	void verifyHashCodeDifferenceForDistinctObjects() {
		LoginPostRequest loginPostRequest1 = new LoginPostRequest();
		loginPostRequest1.setUsername("testUser1");
		loginPostRequest1.setPassword("testPass123");
		LoginPostRequest loginPostRequest2 = new LoginPostRequest();
		loginPostRequest2.setUsername("testUser2");
		loginPostRequest2.setPassword("testPass456");
		int hashCode1 = loginPostRequest1.hashCode();
		int hashCode2 = loginPostRequest2.hashCode();
		assertNotEquals(hashCode1, hashCode2, "The hash code is not different for distinct objects.");
	}

}